### ISSUE TITLE
How do I pass an array of alpha values to vary opacity of points according to weights?

### ISSUE THREAD

**Issue by Rob685** [dfm/corner.py#185]
I'm plotting a corner plot with _only_ points, the histograms, but no contours. I have a normalized array of values that represent weights for each point in the plot. I'm aware that in `matpltolib` >= 3.4, passing an array of alpha values to `plt.scatter` is easily done with `plt.scatter(x,y, alpha=array)`, but corner.corner uses the `plt.plot` method to plot the scatter points. It turns out that the `plot` method doesn't have this convenient feature. I've found solutions to this problem for `plot` (e.g., [here](https://stackoverflow.com/questions/43589232/how-can-i-change-the-alpha-value-dynamically-in-matplotlib-python/43614365)), but the applications to `corner` haven't worked out. What's the best way to accomplish without hacking (and potentially messing up) `corner`?

**Comment by dfm** [comment]
I don't know of a great way to do this without switching corner to use scatter instead of plot, unfortunately. In the long run, I'd be happy to switch officially, but we'd want to phase it in for backwards compatibility. 

For now, your best bet might be to pass `plot_datapoints=False` and then plot the samples manually (using scatter with zorder) following the custom plotting tutorial: https://corner.readthedocs.io/en/latest/pages/custom.html

**Comment by Rob685** [comment]
Thanks for the prompt response, and the suggestion! I appreciate it.
