### ISSUE TITLE
np.zeros () line 535

### ISSUE THREAD

**Issue by pennalima** [dfm/corner.py#81]
Hi all,

Besides the last modification on line 213, I think we also have to define the argument of np.zeros function (on line 535) as int. 
These are the messages I got:

/numpy/lib/function_base.py:564: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  n = np.zeros(bins, ntype)
/numpy/lib/function_base.py:600: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  n += np.bincount(indices, weights=tmp_w, minlength=bins).astype(ntype)

Thanks in advance.

Best,
Mariana Penna Lima

**Comment by dfm** [comment]
Line 535 will already always have type `int`… I expect that you're somehow still running with an older version. Have you updated to the GitHub master branch? If you're convinced that you've updated everything, please send some code that throws this warning because I can't reproduce it after #79.

Thanks!

**Comment by pennalima** [comment]
Dear Dan,

Thanks for the quick answer. Everything is properly working! 
The problem was in another part of my code. 
Sorry for bothering you.

Best,
Mariana
