### ISSUE TITLE
Plot two corner plots on top of each other

### ISSUE THREAD

**Issue by samscibelli** [dfm/corner.py#82]
Hello, 

I was wondering, is there was a way to plot two separate corner plots on top of each other? Perhaps in different colors? 

Thanks!

**Comment by dfm** [comment]
Yep. You can use the `fig` keyword argument to `corner`.

```
fig = corner.corner(samples1)
corner.corner(samples2, fig=fig)
```

It's useful to combine this with the `range` argument to keep reasonable ranges on the plots.

**Comment by drphilmarshall** [comment]
Example here:
https://github.com/tommasotreu/AARV/blob/master/figures/DdtDa.ipynb

I forget how to change the filled contours alpha values to make them
translucent, though.

**Comment by albin-n** [comment]
I'm trying to do the same at the moment, I would like to plot two corner plots on top of each other, but I can't access the example here https://github.com/tommasotreu/AARV/blob/master/figures/DdtDa.ipynb

Can I access it from somewhere else?
Thanks!

**Comment by drphilmarshall** [comment]
I beg your pardon - that notebook got tidied away, to

https://github.com/tommasotreu/AARV/blob/master/attic/spare-or-old-figures/DdtDa.ipynb

**Comment by tousifislam** [comment]
I tried following the links https://github.com/tommasotreu/AARV/blob/master/attic/spare-or-old-figures/DdtDa.ipynb and it worked. However, the 1d histograms (for two different samples) are not being plotted properly. One of the 1d hist overshoots the range. It seems they are not getting normalised. Any suggestion?
Thanks for reading!

**Comment by dfm** [comment]
Yeah - that is annoying behavior. The way that I generally deal with it is to use the `weights` argument. Something like the following:

```python
samples1 = np.array(...
samples2 = np.array(...
fig = corner.corner(samples1)
corner.corner(samples2, fig=fig, weights=np.ones(len(samples2))*len(samples1)/len(samples2))
```

Hope that helps!

**Comment by alulujasmine** [comment]
Hi,
I am writing to inquire how to overlay contours which share violently different ranges using `fig=fig` in corner.py.

Four contours share similar ranges and can be overlayed smoothly with the setting `range=[(0,0.6),(-2,0),(-5,5)]`. 

But when overlaying the other two contours with these fours contours with the setting `range=[(0,0.6),(-2,0),(-5,5)]`, it turned out to be an error. 

The error is as follows:
`Miniconda3-install\lib\site-packages\corner\core.py:775: UserWarning: Attempting to set identical bottom == top == 0 results in singular transformations; automatically expanding.
  return ax.set_ylim(new_ylim)
Miniconda3-install\lib\site-packages\corner\core.py:583: RuntimeWarning: invalid value encountered in true_divide
  sm /= sm[-1]
WARNING:root:Too few points to create valid contours`

These two contours can be overlayed together with much smaller ranges. 

How can I overlay these two contours with those four contours?

**Comment by divyajyoti09** [comment]
For two contours, how does one put the `show_titles` such that values from both the contours get put in the title side by side.. something like this:
![1167_1364_posterior_Mc_eta_M_dist_incl](https://user-images.githubusercontent.com/50514405/159244897-7d5ba5ff-99b9-4451-bc46-f905db397c2f.png)

**Comment by dfm** [comment]
@divyajyoti09 - there is no built in support for this, but you can manually set the titles using the [Custom plotting tutorial](https://corner.readthedocs.io/en/latest/pages/custom.html) to access the axes directly.

**Comment by alchzh** [comment]
> For two contours, how does one put the `show_titles` such that values from both the contours get put in the title side by side.. something like this: 

I ran into this problem recently (matplotlib) and figured out a way to monkey-patch Axes.set_title() to still let corner.py handle the actual content in the titles.

https://gist.github.com/alchzh/7f5fb3d01e53b2ad737db486d065d1a0
